name: Testing

on:
  push:
    branches:
      - next
      - feat/*
      - fix/*

jobs:
  release_alpha:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: node.js 14
        uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/

      - name: installing
        run: npm ci

      - name: linters
        uses: wearerequired/lint-action@v2
        with:
          prettier: true
          prettier_extensions: ts,js,json,md

      - name: testing
        run: npm test

      - name: building
        run: npm run build
